### ISSUE TITLE
Traceback - from cleaning

### ISSUE THREAD

**Issue by RobinGall2910** [RobinGall2910/RobTheBoat#3]
Traceback (most recent call last):
  File "/root/RobTheBoatBot/musicbot/bot.py", line 1695, in on_message
    response = await handler(**handler_kwargs)
  File "/root/RobTheBoatBot/musicbot/bot.py", line 1481, in cmd_clean
    await self.delete_message(entry)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 1147, in delete_message
    yield from utils._verify_successful_response(response)
  File "/usr/local/lib/python3.5/site-packages/discord/utils.py", line 219, in _verify_successful_response
    raise NotFound(response, message, text)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message

Message was removed, and it tried to remove it again, though it did not exist afterwards. Will remove this later..

**Comment by RobinGall2910** [comment]
reset the command from the origin repo.
