### ISSUE TITLE
.gsh - Traceback

### ISSUE THREAD

**Issue by RobinGall2910** [RobinGall2910/RobTheBoat#5]
I was supposed to fix it right now, but I'll do it for tomorrow.

Traceback (most recent call last):
  File "/root/RobTheBoatBot/musicbot/bot.py", line 1717, in on_message
    response = await handler(**handler_kwargs)
  File "/root/RobTheBoatBot/musicbot/bot.py", line 128, in wrapper
    return await func(self, *args, **kwargs)
  File "/root/RobTheBoatBot/musicbot/bot.py", line 708, in cmd_gsh
    await self.change_status('.help for help!')
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 1571, in change_status
    raise InvalidArgument('game must be of Game or None')
discord.errors.InvalidArgument: game must be of Game or None

'Twas suppose to set it was "'.help for help!" obviously.

**Comment by RobinGall2910** [comment]
Fixed, committing later.
